exports.swmt = ["abwiki", "afwikibooks", "afwikiquote", "akwiki", "amwiktionary", "anwiktionary", "angwiki", "angwiktionary", "arwikibooks", "arwikinews", "arwikiquote", "arwikiversity",
    "arcwiki", "aswiki", "avwiki", "aywiki", "aywiktionary", "azwikibooks", "azwikiquote", "azwikisource", "bawikibooks", "bewiktionary", "bewikibooks", "bewikiquote", "bewikisource",
    "bgwikibooks", "bgwikiquote", "bgwikisource", "bhwiki", "biwiki", "bjnwiki", "bmwiki", "bnwikibooks", "bowiki", "brwikiquote", "brwikisource", "bswiktionary", "bswikibooks", "bswikinews",
    "bswikiquote", "bswikisource", "bxrwiki", "cawikibooks", "cawikinews", "cawikiquote", "cawikisource", "cbk_zamwiki", "chwiki", "chrwiki", "chrwiktionary", "chywiki", "cowiki",
    "cowiktionary", "crwiki", "cswikibooks", "cswikinews", "cswikiversity", "csbwiki", "csbwiktionary", "cuwiki", "cvwikibooks", "cywikibooks", "cywikiquote", "cywikisource", "dawikibooks",
    "dawikiquote", "dawikisource", "dewikiquote", "dsbwiki", "dvwiki", "dvwiktionary", "dzwiki", "eewiki", "elwikibooks", "elwikinews", "elwikiquote", "elwikiversity", "eowikibooks",
    "eowikinews", "eowikiquote", "eowikisource", "eswikibooks", "eswikiquote", "eswikiversity", "etwikibooks", "etwikiquote", "etwikisource", "euwikibooks", "euwikiquote", "extwiki",
    "fawikibooks", "fawikinews", "fawikiquote", "ffwiki", "fiwikibooks", "fiwikinews", "fiwikiquote", "fiwikiversity", "fiu_vrowiki", "fjwiki", "fowiktionary", "fowikisource", "frwikiquote",
    "frwikivoyage", "frpwiki", "furwiki", "fywikibooks", "gawiktionary", "gagwiki", "ganwiki", "gdwiktionary", "glwikibooks", "glwikiquote", "glwikisource", "glkwiki", "gnwiki", "gnwiktionary",
    "gotwiki", "guwiktionary", "guwikiquote", "gvwiki", "gvwiktionary", "hawiktionary", "hakwiki", "hawwiki", "hewikibooks", "hewikinews", "hewikiquote", "hiwikibooks", "hiwikiquote", "hifwiki",
    "hrwikibooks", "hrwikiquote", "hrwikisource", "hsbwiktionary", "huwikiquote", "hywikibooks", "hywikiquote", "iawiktionary", "iawikibooks", "idwikibooks", "idwikiquote", "idwikisource",
    "iewiki", "iewiktionary", "igwiki", "ikwiki", "iswikibooks", "iswikiquote", "iswikisource", "itwikiversity", "iuwiki", "iuwiktionary", "jawikinews", "jawikiquote", "jawikiversity", "jbowiki",
    "jbowiktionary", "kawikibooks", "kawikiquote", "kaawiki", "kabwiki", "kbdwiki", "kgwiki", "kiwiki", "kkwiktionary", "kkwikibooks", "klwiki", "klwiktionary", "kmwiki", "kmwiktionary",
    "kmwikibooks", "knwikiquote", "knwikisource", "kowikibooks", "kowikinews", "kowikiquote", "koiwiki", "krcwiki", "kswiki", "kswiktionary", "kshwiki", "kuwikibooks", "kuwikiquote", "kvwiki",
    "kwwiki", "kwwiktionary", "kywikibooks", "kywikiquote", "lawikibooks", "lawikiquote", "lawikisource", "ladwiki", "lbwiktionary", "lbewiki", "lezwiki", "lgwiki", "liwikibooks", "liwikiquote",
    "liwikisource", "lnwiki", "lnwiktionary", "lowiki", "ltwikibooks", "ltwikiquote", "ltwikisource", "ltgwiki", "mdfwiki", "mgwikibooks", "miwiki", "miwiktionary", "mkwiktionary", "mkwikibooks",
    "mkwikisource", "mlwikibooks", "mlwikiquote", "mnwiktionary", "mrwiktionary", "mrwikibooks", "mrwikiquote", "mrwikisource", "mswiktionary", "mswikibooks", "mtwiki", "mtwiktionary", "mwlwiki",
    "myvwiki", "nawiki", "nawiktionary", "nahwiki", "nahwiktionary", "ndswiktionary", "nds_nlwiki", "newiktionary", "newikibooks", "nlwikibooks", "nlwikinews", "nlwikiquote", "nlwikisource",
    "nlwikivoyage", "nnwikiquote", "nowikibooks", "nowikinews", "nowikiquote", "nowikisource", "novwiki", "nrmwiki", "nsowiki", "nywiki", "ocwikibooks", "omwiki", "pawikibooks", "pagwiki",
    "pamwiki", "papwiki", "pcdwiki", "pdcwiki", "pflwiki", "piwiki", "pihwiki", "plwikibooks", "pnbwiktionary", "pntwiki", "ptwikiquote", "ptwikiversity", "quwiktionary", "rmwiki", "rmywiki",
    "rnwiki", "rowikibooks", "rowikinews", "rowikiquote", "roa_rupwiki", "roa_rupwiktionary", "roa_tarawiki", "ruwikibooks", "ruwikiversity", "ruwikivoyage", "ruewiki", "rwwiki", "rwwiktionary",
    "sawiktionary", "sawikibooks", "sahwikisource", "scwiki", "sdwiktionary", "sewiki", "sgwiki", "sgwiktionary", "siwiktionary", "siwikibooks", "skwikibooks", "skwikiquote", "skwikisource",
    "slwikibooks", "slwikiquote", "slwikiversity", "smwiki", "smwiktionary", "snwiki", "sowiki", "sowiktionary", "sqwikibooks", "sqwikinews", "sqwikiquote", "srwikibooks", "srwikiquote",
    "srnwiki", "sswiki", "sswiktionary", "stwiki", "stwiktionary", "stqwiki", "suwiktionary", "suwikiquote", "svwikibooks", "svwikinews", "svwikiquote", "svwikiversity", "svwikivoyage",
    "tawikibooks", "tawikinews", "tawikiquote", "tewikibooks", "tewikiquote", "tetwiki", "tgwikibooks", "thwikibooks", "thwikiquote", "thwikisource", "tiwiki", "tiwiktionary", "tkwiki",
    "tkwiktionary", "tlwikibooks", "tnwiki", "tnwiktionary", "towiki", "tpiwiki", "tpiwiktionary", "trwikibooks", "trwikiquote", "tswiki", "tswiktionary", "ttwiktionary", "ttwikibooks",
    "tumwiki", "twwiki", "tywiki", "udmwiki", "ugwiki", "ugwiktionary", "ukwikibooks", "ukwikinews", "ukwikiquote", "urwikibooks", "urwikiquote", "uzwikiquote", "vewiki", "vecwikisource",
    "vepwiki", "viwikibooks", "viwikiquote", "vlswiki", "wowiki", "wowiktionary", "wowikiquote", "xalwiki", "xhwiki", "yiwiktionary", "yiwikisource", "zawiki", "zeawiki", "zhwikibooks", "zhwikiquote",
    "zh_min_nanwikisource", "zuwiki", "zuwiktionary", "aswikisource", "eswikivoyage", "kowikiversity", "ptwikivoyage", "rowikivoyage", "sawikiquote", "elwikivoyage", "hewikivoyage", "ukwikivoyage",
    "vecwiktionary", "tyvwiki", "viwikivoyage", "arwikimedia", "bdwikimedia", "bewikimedia", "betawikiversity", "brwikimedia", "cowikimedia", "dkwikimedia", "etwikimedia", "fiwikimedia", "mkwikimedia",
    "mxwikimedia", "nlwikimedia", "nowikimedia", "nycwikimedia", "outreachwiki", "plwikimedia", "ruwikimedia", "sewikimedia", "trwikimedia", "uawikimedia", "zhwikivoyage", "fawikivoyage",
    "cawikimedia", "labswiki", "orwikisource", "gomwiki", "adywiki", "jamwiki", "tcywiki", "olowiki", "fiwikivoyage", "pawikisource", "dtywiki", "ptwikimedia", "atjwiki", "kbpwiki", "dinwiki",
    "hiwikiversity", "hiwikivoyage", "hifwiktionary", "euwikisource", "inhwiki", "lfnwiki", "bnwikivoyage", "pmswikisource", "pswikivoyage", "sahwikiquote", "satwiki", "zhwikiversity", "wikimaniawiki",
    "liwikinews", "shnwiki", "yuewiktionary", "hywwiki", "hiwikisource", "nqowiki", "banwiki", "gcrwiki", "minwiktionary", "mnwwiki", "shywiktionary", "szywiki", "awawiki", "gomwiktionary", "arywiki",
    "lijwikisource", "lldwiki", "jawikivoyage", "smnwiki", "eowikivoyage", "madwiki", "skrwiki", "wawikisource", "bclwiktionary", "diqwiktionary", "niawiki", "niawiktionary", "trwikivoyage", "altwiki",
    "mniwiki", "mniwiktionary", "mnwwiktionary", "taywiki", "trvwiki", "banwikisource", "dagwiki", "shiwiki", "afwiki", "alswiki", "amwiki", "anwiki", "arwikisource", "astwiki", "azwiki", "bat_smgwiki",
    "brwiki", "bswiki", "cswiktionary", "cywiki", "dewikisource", "diqwiki", "elwikisource", "enwikiversity", "eowiki", "eswiktionary", "fiwikisource", "frwikinews", "gawiki", "hrwiktionary", "htwiki",
    "huwikibooks", "huwiktionary", "hywiktionary", "iowiki", "iswiktionary", "jvwiki", "kawiki", "kkwiki", "kowikisource", "kuwiki", "kywiki", "lawiki", "lawiktionary", "lbwiki", "liwiki", "lmowiki",
    "lvwiki", "maiwiki", "map_bmswiki", "metawiki", "mgwiki", "mlwiki", "mlwiktionary", "mrjwiki", "newwiki", "plwikinews", "plwikiquote", "pswiki", "sawiki", "siwiki", "skwiktionary", "sqwiki",
    "srwikisource", "tawiki", "tewiki", "ttwiki", "urwiki", "zh_classicalwiki", "zh_yuewiki", "afwiktionary", "barwiki", "be_x_oldwiki", "be_tarask", "bnwikisource", "crhwiki", "cvwiki", "dewikibooks", "dewiktionary",
    "eswikinews", "eswikisource", "fawiktionary", "fywiki", "glwiktionary", "guwiki", "hewikisource", "hewiktionary", "hiwiktionary", "hsbwiki", "huwikisource", "iawiki", "kawiktionary", "knwiki",
    "ltwiktionary", "lvwiktionary", "mediawikiwiki", "mznwiki", "ndswiki", "newiki", "nlwiktionary", "nnwiktionary", "ocwiki", "ptwikibooks", "ptwikinews", "ptwikisource", "ptwiktionary", "quwiki",
    "ruwikiquote", "ruwikisource", "sawikisource", "scowiki", "skwiki", "slwiki", "swwiktionary", "tawikisource", "tgwiki", "tgwiktionary", "thwiktionary", "uzwiki", "viwikisource", "vowiki", "vowiktionary",
    "yowiki", "zh_min_nanwiki", "arwiktionary", "astwiktionary", "bnwiki", "brwiktionary", "cawiktionary", "cswikiquote", "dewikinews", "enwikibooks", "enwikiquote", "etwiki", "fiwiktionary", "fjwiktionary",
    "frwikibooks", "frwikiversity", "gdwiki", "guwikisource", "hiwiki", "hrwiki", "incubatorwiki", "kuwiktionary", "nowiktionary", "nvwiki", "oswiki", "plwikisource", "plwikivoyage", "rowikisource",
    "ruwikinews", "ruwiktionary", "sahwiki", "slwiktionary", "srwikinews", "suwiki", "svwikisource", "swwiki", "szlwiki", "tewikisource", "tewiktionary", "thwiki", "tlwiki", "ukwiktionary", "sourceswiki",
    "wuuwiki", "acewiki", "azwiktionary", "bewiki", "bgwiki", "bgwiktionary", "bpywiki", "bugwiki", "cdowiki", "ckbwiki", "cswikisource", "dawiktionary", "elwiktionary", "eowiktionary", "etwiktionary",
    "fowiki", "gorwiki", "hawiki", "hywiki", "idwiktionary", "ilowiki", "iowiktionary", "iswiki", "jvwiktionary", "liwiktionary", "mhrwiki", "mnwiki", "orwiktionary", "plwiktionary", "pnbwiki", "pswiktionary",
    "rowiktionary", "sdwiki", "specieswiki", "srwiktionary", "svwiktionary", "trwikisource", "trwiktionary", "viwiktionary", "wawiki", "xmfwiki", "yiwiki", "zhwikinews", "zhwikisource", "zh_min_nanwiktionary",
    "arzwiki", "bawiki", "bclwiki", "bnwiktionary", "cewiki", "cywiktionary", "dewikiversity", "euwiki", "euwiktionary", "fawikisource", "frrwiki", "fywiktionary", "glwiki", "hywikisource", "knwiktionary",
    "kowiktionary", "kywiktionary", "lowiktionary", "ltwiki", "minwiki", "mlwikisource", "mswiki", "mywiki", "mywiktionary", "ocwiktionary", "omwiktionary", "orwiki", "pawiki", "pawiktionary", "shwiktionary",
    "slwikisource", "sqwiktionary", "tawiktionary", "tlwiktionary", "ukwikisource", "urwiktionary", "uzwiktionary", "wawiktionary"];
exports.lt300 = ["cebwiki", "dewikivoyage", "emlwiki", "enwikinews", "frwikisource", "itwiktionary", "itwikibooks", "itwikinews", "itwikiquote", "itwikisource", "itwikivoyage",
    "jawiktionary", "jawikibooks", "jawikisource", "lijwiki", "mgwiktionary", "mkwiki", "mrwiki", "napwiki", "nnwiki", "pmswiki", "scnwiki", "scnwiktionary", "shwiki", "simplewiktionary",
    "vecwiki", "warwiki", "zhwiktionary", "azbwiki", "napwikisource", "shnwiktionary", "avkwiki", "skrwiktionary"];
exports.groupFilt = ["sysop", "editor", "autoreviewer", "confirmed", "extendedconfirmed", "filemover", "patroller", "templateeditor", "autopatrolled", "autoreview", "closer",
    "rollbacker", "translator", "translationadmin", "engineer", "global-renamer", "oversight", "reviewer", "bureaucrat", "interface-admin", "checkuser"];
exports.customSandBoxes = {
    "mediawikiwiki": ["VisualEditor:Test"],
    "simplewiki": ["Wikipedia:Introduction"],
    "eswiki": ["Wikipedia:Zona de pruebas/1", "Wikipedia:Zona de pruebas/2", "Wikipedia:Zona de pruebas/3", "Wikipedia:Zona de pruebas/4", "Wikipedia:Zona de pruebas/5",
        "Wikipedia:Zona de pruebas/6", "Wikipedia:Zona de pruebas/7", "Wikipedia:Zona de pruebas/8", "Wikipedia:Zona de pruebas/9", "Wikipedia:Zona de pruebas/10"],
    "wikidatawiki": ["Q4115189", "Q13406268", "Q15397819", "Property:P368", "Property:P369", "Property:P370", "Property:P578", "Property:P626", "Property:P855",
        "Property:P1106", "Property:P1450", "Property:P2368", "Property:P2535", "Property:P2536", "Property:P4047", "Property:P5188", "Property:P5189", "Property:P6604",
        "Lexeme:L123", "Lexeme:L1234", "Q17339402", "Q85408509", "Q85409163", "Q16943273", "Q85409446", "Q85409596", "Q85409310", "Q17566023", "Q17578745", "Q85408938"]
};
exports.namespaces = ["<font color='green'>Main</font>", "<font color='tomato'>Talk</font>", "<font color='tomato'>User</font>", "<font color='tomato'>User talk</font>", "<font color='orange'>Project</font>", "<font color='tomato'>Project talk</font>", "<font color='orange'>File</font>", "<font color='tomato'>File talk</font>", "<font color='tomato'>MediaWiki</font>", "<font color='tomato'>MediaWiki talk</font>", "<font color='orange'>Template</font>", "<font color='tomato'>Template talk</font>", "<font color='orange'>Help</font>", "<font color='tomato'>Help talk</font>", "<font color='orange'>Category</font>", "<font color='tomato'>Category talk</font>"];
exports.userAgent = "SWViewer/1.4+; swviewer@tools.wmflabs.org; SSE-proxy, TheTalk; NodeJS: request";